# fly.toml app configuration file generated for titanic-forked on 2023-08-09T11:36:03+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "titanic-forked"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
